import React from 'react';

const DietResult = ({ plan, clientName }) => {
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="mt-5">
      
      {/* --- ACTION BAR (Visible only on screen) --- */}
      <div className="d-flex justify-content-between align-items-center mb-4 no-print">
        <h4 className="text-white m-0">Generated Plan</h4>
        <button onClick={handlePrint} className="btn btn-success fw-bold">
          <i className="bi bi-whatsapp"></i> Save / Print PDF
        </button>
      </div>

      {/* --- THE PRINTABLE TICKET --- */}
      {/* We give this a white background because paper is white */}
      <div className="card border-0 shadow-lg printable-area" style={{background: 'white', color: 'black'}}>
        
        {/* Header / Branding */}
        <div className="card-header bg-black text-white p-4 text-center">
          <h2 className="fw-bold text-uppercase" style={{letterSpacing: '2px'}}>IRON MUSCLE GYM</h2>
          <p className="m-0 small text-secondary">SALEM, TAMIL NADU • EST. 2024</p>
        </div>

        {/* Client Details Section */}
        <div className="card-body p-5">
          <div className="row mb-4 border-bottom pb-3">
             <div className="col-6">
                <p className="text-muted small m-0 text-uppercase">Member Name</p>
                <h5 className="fw-bold">{clientName}</h5>
             </div>
             <div className="col-6 text-end">
                <p className="text-muted small m-0 text-uppercase">Date</p>
                <h5 className="fw-bold">{new Date().toLocaleDateString()}</h5>
             </div>
          </div>

          {/* THE AI CONTENT INJECTED HERE */}
          <div className="diet-content"  >
            <div style={{color: 'black'}} dangerouslySetInnerHTML={{ __html: plan }}></div>
            
          </div>

          {/* Footer */}
          <div className="mt-5 p-3 bg-light text-center border-top">
            <p className="m-0 fw-bold small text-muted">Authorized by Head Trainer</p>
            <p className="small text-danger fst-italic">Generated by GymAI Tech</p>
          </div>

        </div>
      </div>
    </div>
  );
};

export default DietResult;